Repository incubateur-ademe/quefairedemesobjets, pull requests merged in 2025-08, with the labels that each got.

#1831 L'option keep_empty n'est applicable que pour la modification de parent
  dags/cluster/dags/cluster_acteur_suggestions.py
  dags/cluster/tasks/business_logic/cluster_acteurs_parents_choose_data.py
  dags/tests/cluster/tasks/business_logic/test_cluster_acteurs_parents_choose_data.py
Labels: bug, patch

#1837 Purge des logs de DB toutes les heures
  .secrets.baseline
  airflow-scheduler.Dockerfile
  dags/.env.template
  dags/shared/config/schedules.py
  dags/shared/config/tags.py
  dags/tools/dags/purge_log_db.py
  docker-compose.yml
  scripts/infrastructure/purge_db_logs.sh
Labels: bug

#1830 Ajout d'un expiration lors de la cération du backup
  scripts/infrastructure/backup-db.sh
Labels: technical, patch

#1844 Nettoyage des logs sur 2 bases de données
  scripts/infrastructure/purge_db_logs.sh
Labels: technical

#1845 [Clustering] Parfois le parent à supprimer existe toujours
  data/models/changes/acteur_delete_as_parent.py
  unit_tests/data/models/changes/test_acteur_delete_as_parent.py
Labels: bug, patch

#1846 Mise à jour de l'environnement de dev avec plusieurs DB
  .env.template
  .github/workflows/ci.yml
  .gitignore
  .secrets.baseline
  Makefile
  core/settings.py
  core/test_settings.py
  dags/.env.template
  dags/acteurs/dags/compute_acteur.py
  dags/e2e_tests/test_e2e_dag_template_read_db.py
  dags/shared/tasks/database_logic/db_manager.py
  dags/views/view_acteur_tous.py
  docker-compose.yml
  qfdmo/management/commands/setup_dbt_schemas.py
Labels: technical

#1858 ajout de la colonne consignes_dacces dans la configuration DBT
  dags/.env.template
  dbt/macros/table/macro_acteur.sql
  dbt/models/base/acteurs/schema.yml
  dbt/models/exposure/acteurs/carte/schema.yml
  dbt/models/exposure/acteurs/exhaustive/schema.yml
  dbt/models/intermediate/acteurs/int_acteur.sql
  dbt/models/intermediate/acteurs/schema.yml
  dbt/models/marts/acteurs/carte/schema.yml
  dbt/models/marts/acteurs/exhaustive/schema.yml
  dbt/models/marts/acteurs/opendata/schema.yml
Labels: enhancement, patch

#1865 recreation du server/schema distant après chaque évolution de la DB
  bin/post_deploy
Labels: technical, patch

#1866 Recherche des suggestions selon le texte de metadata
  data/admin.py
Labels: enhancement, minor

#1857 Suppression du DAG compute_final_acteur
  dags/compute_acteurs/__init__.py
  dags/compute_acteurs/dags/create_final_actors.py
  dags/compute_acteurs/tasks/airflow_logic/__init__.py
  dags/compute_acteurs/tasks/airflow_logic/compute_acteur_services_task.py
  dags/compute_acteurs/tasks/airflow_logic/compute_acteur_task.py
  dags/compute_acteurs/tasks/airflow_logic/compute_labels_task.py
  dags/compute_acteurs/tasks/airflow_logic/compute_ps_task.py
  dags/compute_acteurs/tasks/airflow_logic/db_data_write_task.py
  dags/compute_acteurs/tasks/airflow_logic/deduplicate_acteur_services_task.py
  dags/compute_acteurs/tasks/airflow_logic/deduplicate_acteur_sources_task.py
  dags/compute_acteurs/tasks/airflow_logic/deduplicate_labels_task.py
  dags/compute_acteurs/tasks/airflow_logic/deduplicate_propositionservices_task.py
  dags/compute_acteurs/tasks/business_logic/__init__.py
  dags/compute_acteurs/tasks/business_logic/compute_acteur.py
  dags/compute_acteurs/tasks/business_logic/compute_acteur_services.py
  dags/compute_acteurs/tasks/business_logic/compute_labels.py
  dags/compute_acteurs/tasks/business_logic/compute_ps.py
  dags/compute_acteurs/tasks/business_logic/db_data_write.py
  dags/compute_acteurs/tasks/business_logic/deduplicate_acteur_services.py
  dags/compute_acteurs/tasks/business_logic/deduplicate_acteur_sources.py
  dags/compute_acteurs/tasks/business_logic/deduplicate_labels.py
  dags/compute_acteurs/tasks/business_logic/deduplicate_propositionservices.py
  dags/compute_acteurs/tasks/transform/merge_and_deduplicate.py
  dags/shared/tasks/airflow_logic/dbt_command_task.py
  dags/sources/tasks/transform/formatter.py
  dags/sources/tasks/transform/transform_column.py
  dags/sources/tasks/transform/transform_df.py
  dags/tests/compute_acteurs/business_logic/test_compute_acteur.py
  dags/tests/compute_acteurs/business_logic/test_compute_acteur_services.py
  dags/tests/compute_acteurs/business_logic/test_compute_labels.py
  dags/utils/task_names.py
Labels: technical, minor

#1855 Utilisation d'instance DB-PLAY2-NANO en preprod
  infrastructure/environments/preprod/database/.terraform.lock.hcl
  infrastructure/environments/preprod/database/terragrunt.hcl
Labels: technical, patch

#1784 💣 Meilleure gestion de la copie de tables pour éviter que la base de données grossisse de manière exponentielle
  Makefile
  bin/post_deploy
  core/settings.py
  core/utils.py
  dags/acteurs/tasks/business_logic/replace_acteur_table.py
  dags/clone/config/sql/validation/ae_etablissement/validate_join_acteurs_count_siret.sql
  dags/clone/config/sql/validation/ae_unite_legale/validate_join_acteurs_count_siren.sql
  dbt/README.md
  dbt/macros/field/coalesce_empty.sql
  dbt/models/source/source_acteur.yml
  dbt/models/source/source_enrich.yml
  dbt/profiles.yml
  docs/comment-faire/stack-data.md
  poetry.lock
  pyproject.toml
  qfdmo/management/commands/create_remote_db_server.py
  qfdmo/management/commands/setup_dbt_schemas.py
  qfdmo/migrations/0164_rebuild_remote_server.py
Labels: airflow

#1868 [Cluster] Normaliser aussi le paramètre de recherche par le nom
  dags/cluster/tasks/business_logic/cluster_acteurs_read/orphans.py
Labels: bug, patch

#1869 Résolution d'une régresseion dans la CI : test de bout en bout
  .github/workflows/ci.yml
Labels: bug, frontend, patch

#1843 Infrastructure : container registry namespace
  Makefile
  infrastructure/environments/prod/container_registry/.terraform.lock.hcl
  infrastructure/environments/prod/container_registry/terragrunt.hcl
  infrastructure/modules/container_registry/main.tf
  infrastructure/modules/container_registry/terraform.tfvars.example
Labels: technical

#1871 Infra database : correction nom de variable
  infrastructure/modules/database/main.tf
Labels: technical

#1867 CI Docker : utilisation du cache
  .github/workflows/docker.yml
Labels: technical

#1854 L'option exclusivité de source doit prendre en compte les sources des parents
  dags/cluster/tasks/business_logic/cluster_acteurs_clusters.py
  dags/cluster/tasks/business_logic/cluster_acteurs_read/for_clustering.py
  dags/cluster/tasks/business_logic/cluster_acteurs_read/orphans.py
  dags/cluster/tasks/business_logic/cluster_acteurs_read/parents.py
  dags/cluster/tasks/business_logic/misc/cluster_exclude_intra_source.py
  dags/cluster/tasks/business_logic/misc/df_sort.py
  dags/tests/cluster/tasks/business_logic/test_cluster_acteurs_clusters.py
  dags/tests/cluster/tasks/business_logic/test_cluster_acteurs_clusters_prepare.py
  dags/tests/cluster/tasks/business_logic/test_cluster_acteurs_exclude_intra_source.py
  dags/tests/cluster/tasks/business_logic/test_cluster_acteurs_read_parents.py
Labels: bug, patch

#1873 Mise à jour d'Airflow en version 2.11.0
  airflow-scheduler.Dockerfile
  airflow-webserver.Dockerfile
  poetry.lock
  pyproject.toml
Labels: dependencies, python, minor

#1874 Affichage des consignes d'accès et initialisation pour les déchèteries
  jinja2/qfdmo/acteur/tabs/about_panel.html
  jinja2/qfdmo/acteur/tabs/sections/consignes_dacces.html
  qfdmo/management/commands/fill_consignes_dacces.py
Labels: enhancement, minor

#1894 Ajout du mapping CITEO vers emballage reemployable
  dags/sources/config/db_mapping.json
Labels: enhancement, minor

#1893 Annuaire-Entreprise a modifié ses endpoint
  dags/clone/dags/clone_ae_etablissement.py
  dags/clone/dags/clone_ae_unite_legale.py
Labels: bug, patch

#1892 Correction du lancement du Dag export_opendata une fois par semaine
  dags/acteurs/dags/export_opendata.py
Labels: bug, patch

#1889 CD Preprod pour Airflow sur Scaleway
  .github/workflows/_deploy-airflow.yml
  .github/workflows/_scaleway_container_deploy.yml
  .github/workflows/airflow_docker.yml
  .github/workflows/cd.yml
Labels: technical, airflow

#1836 Accessibilité RGAA conforme 100% - Lot 1
  previews/template_preview.py
  qfdmd/admin.py
  static/to_compile/styles/qfdmd.css
  templates/components/header/header.html
  templates/components/logo/_base.html
  templates/components/logo/_cursor.html
  templates/components/logo/animated.html
  templates/components/logo/header.html
  templates/components/logo/homepage.html
  templates/components/search/view.html
  templates/components/search/widget.html
  templates/modals/share.html
  templates/sites_faciles_content_manager/blocks/breadcrumbs.html
Labels: enhancement

#1917 Le déploiement du docker ne connait pas le conatiner_id avant de définir l'environnement
  .github/workflows/_deploy-airflow.yml
  .github/workflows/_scaleway_container_deploy.yml
Labels: bug

#1922 Ajout de lodash dans les dépendances
  package-lock.json
  package.json
Labels: dependencies, javascript, frontend, technical, minor

#1898 Ajout de la notion de service à domicile
  .env.template
  .vscode/settings.json
  Makefile
  core/admin.py
  core/settings.py
  dags/acteurs/dags/compute_acteur.py
  dags/acteurs/tasks/business_logic/replace_acteur_table.py
  dags/cluster/config/constants.py
  dags/cluster/tasks/business_logic/cluster_acteurs_parents_choose_data.py
  dags/sources/config/airflow_params.py
  dags/sources/dags/source_cma.py
  dags/sources/dags/source_s3.py
  dags/sources/dags/source_sinoe.py
  dags/sources/tasks/business_logic/db_read_acteur.py
  dags/sources/tasks/business_logic/keep_acteur_changed.py
  dags/sources/tasks/transform/transform_df.py
  dags/tests/cluster/tasks/business_logic/test_cluster_acteurs_parents_choose_data.py
  dags/tests/sources/tasks/transform/test_transform_df.py
  dags/tests/utils/test_django.py
  data/models/changes/acteur_create_as_parent.py
  data/models/suggestion.py
  dbt/macros/table/macro_acteur.sql
  dbt/models/base/acteurs/base_perimetreadomicile.sql
  dbt/models/base/acteurs/base_revisionperimetreadomicile.sql
  dbt/models/exposure/acteurs/carte/exposure_carte_perimetreadomicile.sql
  dbt/models/exposure/acteurs/carte/schema.yml
  dbt/models/exposure/acteurs/exhaustive/exposure_exhaustive_perimetreadomicile.sql
  dbt/models/exposure/acteurs/exhaustive/schema.yml
  dbt/models/exposure/acteurs/opendata/exposure_opendata_acteur.sql
  dbt/models/exposure/acteurs/opendata/schema.yml
  dbt/models/intermediate/acteurs/int_acteur.sql
  dbt/models/intermediate/acteurs/int_perimetreadomicile.sql
  dbt/models/marts/acteurs/carte/marts_carte_perimetreadomicile.sql
  dbt/models/marts/acteurs/carte/schema.yml
  dbt/models/marts/acteurs/exhaustive/marts_exhaustive_perimetreadomicile.sql
  dbt/models/marts/acteurs/exhaustive/schema.yml
  dbt/models/marts/acteurs/opendata/marts_opendata_perimetreadomicile.sql
  dbt/models/marts/acteurs/opendata/schema.yml
  dbt/models/source/source_acteur.yml
  dbt/profiles.yml
  qfdmo/admin/acteur.py
  qfdmo/migrations/0001_initial_squashed_0158_alter_carteconfig_slug.py
  qfdmo/migrations/0167_serviceadomicile.py
  qfdmo/migrations/0168_alter_serviceadomicile.py
  qfdmo/models/acteur.py
Labels: enhancement, minor

#1904 Amélioration continue admin Wagtail - lot 19/8
  integration_tests/carte/test_use_carte_config.py
  jinja2/layout/base.html
  jinja2/qfdmo/carte.html
  jinja2/qfdmo/carte/header.html
  jinja2/qfdmo/carte/panels/legend.html
  jinja2/qfdmo/carte/panels/legend_mobile.html
  jinja2/qfdmo/shared/disclaimers/adresse_missing.html
  qfdmd/blocks.py
  qfdmd/management/commands/merge_reusable_content.py
  qfdmd/migrations/0053_produitpage_sous_categorie_objet_and_more.py
  qfdmd/models.py
  qfdmd/templatetags/qfdmd_tags.py
  qfdmd/wagtail_hooks.py
  qfdmo/migrations/0169_rename_hide_legend_carteconfig_cacher_legende_and_more.py
  qfdmo/models/config.py
  qfdmo/urls.py
  qfdmo/views/carte.py
  templates/blocks/carte.html
  templates/components/carte/carte.html
  templates/components/produit/_infotri.html
  templates/components/produit/heading.html
  templates/components/produit/heading_family.html
  templates/qfdmd/family_page.html
  templates/qfdmd/produit_page.html
  templates/sites_faciles_content_manager/blocks/tabs.html
Labels: enhancement, frontend, minor

#1925 Mise à jour et correction avant mise en prod des services à domicile
  dags/sources/tasks/business_logic/db_read_acteur.py
  dags/sources/tasks/business_logic/keep_acteur_changed.py
  dags/sources/tasks/transform/transform_df.py
  dags/tests/sources/tasks/transform/test_transform_df.py
  data/models/changes/acteur_create_as_parent.py
  data/models/suggestion.py
  dbt/models/exposure/acteurs/carte/schema.yml
  dbt/models/exposure/acteurs/exhaustive/schema.yml
  dbt/models/exposure/acteurs/opendata/exposure_opendata_acteur.sql
  dbt/models/intermediate/acteurs/int_perimetreadomicile.sql
  dbt/models/marts/acteurs/carte/schema.yml
  dbt/models/marts/acteurs/exhaustive/schema.yml
  dbt/models/marts/acteurs/opendata/schema.yml
  qfdmo/migrations/0170_update_perimetre_adomicile.py
  qfdmo/models/acteur.py
Labels: enhancement, minor

#1928 Corrige un problème de migration sur la table vueacteur
  qfdmo/migrations/0001_initial_squashed_0158_alter_carteconfig_slug.py
  qfdmo/migrations/0167_serviceadomicile.py
Labels: bug, patch

#1924 Améliorations SEO - Lot 1 : sitemap, adresses
  core/urls.py
  integration_tests/carte/test_acteur_detail.py
  templates/robots.txt
Labels: seo

#1929 Corriger un problème d'erreur lors de la visualisation d'une page Wagtail
  qfdmd/models.py
  qfdmd/templatetags/qfdmd_tags.py
Labels: bug

#1931 Faire en sorte que la selection d'objet soit toujours dispo sur la carte
  core/jinja2_handler.py
Labels: bug, frontend, patch
