Repository incubateur-ademe/quefairedemesobjets, pull requests merged in 2025-05, with the labels that each got.

#1594 :one: Suggestions: migrer vers 1 seul template
  dags/cluster/tasks/business_logic/cluster_acteurs_suggestions/context.py
  dags/cluster/tasks/business_logic/cluster_acteurs_suggestions/prepare.py
  dags/cluster/tasks/business_logic/cluster_acteurs_suggestions/to_db.py
  dags/crawl/config/constants.py
  dags/crawl/tasks/business_logic/crawl_urls_suggest.py
  dags/enrich/tasks/business_logic/enrich_dbt_model_to_suggestions.py
  dags_unit_tests/cluster/tasks/business_logic/test_cluster_acteurs_suggestions_contexte_generate.py
  dags_unit_tests/cluster/tasks/business_logic/test_cluster_acteurs_suggestions_prepare.py
  dags_unit_tests/cluster/tasks/business_logic/test_cluster_acteurs_suggestions_to_db_and_apply.py
  dags_unit_tests/enrich/tasks/test_enrich_suggestions_cities.py
  data/models/changes/acteur_rgpd_anonymize.py
  data/models/suggestion.py
  dbt/models/marts/enrich/marts_enrich_acteurs_villes_candidates.sql
  templates/data/_partials/clustering_suggestion_details.html
  templates/data/_partials/crawl_urls_suggestion_details.html
  templates/data/_partials/dicts_to_table.html
  templates/data/_partials/suggestion_details_changes.html
  templates/data/_partials/value_details.html
  unit_tests/data/models/changes/test_acteur_rgpd_anonymize.py
Labels: bug, enhancement, python, airflow

#1595 🔎 DAGs d'enrichissement: plus de filtres
  dags/enrich/config/__init__.py
  dags/enrich/config/models.py
  dags/enrich/dags/enrich_acteurs_closed.py
  dags/enrich/dags/enrich_acteurs_rgpd.py
  dags/enrich/dags/enrich_acteurs_villes.py
  dags/enrich/dags/enrich_dbt_models_refresh.py
  dags/enrich/tasks/airflow_logic/enrich_config_create_task.py
  dags/enrich/tasks/airflow_logic/enrich_dbt_model_suggest_task.py
  dags/enrich/tasks/airflow_logic/enrich_dbt_models_refresh_task.py
  dags/enrich/tasks/business_logic/enrich_dbt_model_row_to_suggest_data.py
  dags/enrich/tasks/business_logic/enrich_dbt_model_to_suggestions.py
  dags/shared/config/models.py
  dags/utils/airflow_params.py
  dags/utils/dataframes.py
  dags_unit_tests/enrich/config/test_enrich_acteurs_closed_config.py
  dags_unit_tests/enrich/tasks/test_enrich_suggestions_cities.py
  dags_unit_tests/enrich/tasks/test_enrich_suggestions_closed.py
  dags_unit_tests/enrich/tasks/test_enrich_suggestions_rgpd.py
  dags_unit_tests/shared/config/test_shared_config_models.py
  dbt/models/marts/enrich/marts_enrich_acteurs_rgpd_suggest.sql
  dbt/models/marts/enrich/marts_enrich_acteurs_villes_candidates.sql
Labels: enhancement, airflow

#1589 Supression de la metadata des pro filtrés et ajout du nombre d'acteurs impactés
  dags/sources/tasks/airflow_logic/db_data_prepare_task.py
  dags/sources/tasks/airflow_logic/db_write_type_action_suggestions_task.py
  dags/sources/tasks/business_logic/db_data_prepare.py
  dags/sources/tasks/business_logic/source_data_normalize.py
Labels: bug, patch

#1588 Gestion des retour à la ligne de la descriptiion : solution temporaire
  core/jinja2_handler.py
  jinja2/qfdmo/acteur/tabs/sections/description.html
  jinja2/qfdmo/acteur/tabs/sections/horaires.html
Labels: enhancement, minor

#1598 Ignorer le dossier script lors de la collecte des tests par pytest
  pyproject.toml
Labels: technical, minor

#1574 🚪 Acteurs fermés: pas créer de parent
  Makefile
  Procfile.all.dev
  Procfile.django.dev
  dags/acteurs/dags/compute_acteur.py
  dags/clone/config/sql/creation/tables/create_table_ban_lieux_dits.sql
  dags/clone/tasks/business_logic/clone_table_validate.py
  dags/crawl/tasks/business_logic/crawl_urls_suggest.py
  dags/enrich/config/columns.py
  dags/enrich/dags/enrich_dbt_models_refresh.py
  dags/enrich/tasks/business_logic/enrich_dbt_model_to_suggestions.py
  dags_unit_tests/cluster/tasks/business_logic/test_cluster_acteurs_clusters.py
  dags_unit_tests/cluster/tasks/business_logic/test_cluster_acteurs_parents_choose_data.py
  dags_unit_tests/cluster/tasks/business_logic/test_cluster_acteurs_parents_choose_new.py
  dags_unit_tests/cluster/tasks/business_logic/test_cluster_acteurs_read_orphans.py
  dags_unit_tests/crawl/tasks/business_logic/test_crawl_urls_suggest_prepare.py
  dags_unit_tests/e2e/test_e2e_dag_cluster_acteurs_airflow.py
  dags_unit_tests/enrich/tasks/test_enrich_suggestions_closed.py
  dags_unit_tests/shared/tasks/airflow_logic/test_packages_compatibility.py
  dags_unit_tests/sources/tasks/transform/test_transform_df.py
  dags_unit_tests/utils/test_data_serialize_reconstruct.py
  dags_unit_tests/utils/test_django.py
  data/models/changes/__init__.py
  data/models/changes/acteur_create_as_child.py
  data/models/changes/acteur_update_data.py
  data/models/changes/acteur_update_revision.py
  dbt/models/marts/enrich/marts_enrich_acteurs_closed_candidates.sql
  dbt/models/marts/enrich/marts_enrich_acteurs_rgpd_suggest.sql
  dbt/models/marts/enrich/marts_enrich_acteurs_villes_candidates.sql
  dbt/models/source/source_enrich.yml
  docs/explications/data/enrich/README.md
  qfdmo/models/acteur.py
  templates/data/_partials/value_details.html
  unit_tests/data/models/changes/test_acteur_create_as_child.py
  unit_tests/data/models/changes/test_acteur_update_data.py
  unit_tests/data/models/changes/test_acteur_update_revision.py
Labels: enhancement, airflow

#1610 Dédupliquer les lignes qui ont plusieurs EO et prefixé ocab
  dags/sources/dags/source_ocab.py
  dags/sources/tasks/airflow_logic/config_management.py
  dags/sources/tasks/business_logic/source_data_normalize.py
  dags_unit_tests/sources/tasks/business_logic/test_source_data_normalize.py
Labels: enhancement, minor

#1622 Correction pour la gestion des acteurs à anonymiser pour des raisons RGPD
  dbt/models/marts/enrich/marts_enrich_acteurs_closed_candidates.sql
  dbt/models/marts/enrich/marts_enrich_acteurs_rgpd_suggest.sql
  dbt/models/marts/enrich/marts_enrich_acteurs_villes_candidates.sql
Labels: enhancement

#1617 Mise à jour du endpoint CMA reparacteur et adaptation des paramètres du DAG
  dags/sources/config/airflow_params.py
  dags/sources/dags/source_cma.py
  dags/sources/tasks/business_logic/source_data_download.py
  dags/sources/tasks/business_logic/source_data_normalize.py
  dags/sources/tasks/transform/transform_column.py
  dags/sources/tasks/transform/transform_df.py
  dags_unit_tests/sources/tasks/business_logic/test_source_data_normalize.py
  dags_unit_tests/sources/tasks/transform/test_transform_column.py
  dags_unit_tests/sources/tasks/transform/test_transform_df.py
Labels: enhancement, minor

#1616 Correction de la documentation
  Makefile
  docs/Makefile
  docs/README.md
  docs/comment-faire/development/development.md
  docs/explications/README.md
  docs/explications/data/README.md
  docs/explications/data/flux-dbt.md
  docs/explications/data/flux-enrich.md
  docs/explications/data/ingestion-de-source.md
  docs/explications/frontend/README.md
  docs/explications/iframe/iframe.md
  docs/reference/README.md
  docs/reference/data/organisations-des-fichiers.md
  docs/reference/db/prerequis.md
  docs/reference/documentation-technique.md
Labels: bug, documentation, minor

#1623 Ajout de context pour les suggestions d'acteur fermé
  dags/enrich/tasks/business_logic/enrich_dbt_model_to_suggestions.py
  dags_unit_tests/enrich/tasks/test_enrich_suggestions_closed.py
Labels: enhancement, minor

#1628 Correction de la synchro de la base de données
  scripts/restore_prod_to_preprod.sh
Labels: bug, patch

#1627 Correction de la publication de la documentation
  .github/workflows/publish-docs.yml
Labels: bug, documentation, patch

#1632 Mise à jour des seuils de contrôle des tables DBT générées
  dbt/models/exposure/acteurs/carte/schema.yml
  dbt/models/exposure/acteurs/opendata/schema.yml
Labels: bug, patch

#1641 Ajouter le tiret comme separateur possible dans une adresse BAN
  dags/sources/tasks/transform/transform_df.py
  dags/tests/sources/tasks/transform/test_transform_df.py
Labels: enhancement, minor
