Repository incubateur-ademe/quefairedemesobjets, pull requests merged in 2025-07, with the labels that each got.

#1745 🔨 Mise à jour fixtures pour qu'elles s'installent correctement
  Makefile
  e2e_tests/accessibility.spec.ts
  e2e_tests/acteurs.spec.ts
  e2e_tests/assistant.spec.ts
  qfdmo/fixtures/acteurs.json
  qfdmo/fixtures/propositions_services.json
  qfdmo/management/commands/dumpdata_acteurs.py
  qfdmo/management/commands/loadacteurs.py
  qfdmo/management/commands/loaddata_with_computed_fields.py
  qfdmo/models/acteur.py
Labels: frontend, technical

#1757 Modification de la taille du disque de la DB
  infrastructure/environments/preprod/main.tf
  infrastructure/environments/prod/main.tf
Labels: bug

#1759 Afficher les liens vers google maps et annuaire-entreprise sur les parents
  qfdmo/admin/acteur.py
Labels: enhancement, minor

#1737 🇫🇷 Utiliser le header du DSFR
  core/context_processors.py
  previews/template_preview.py
  qfdmd/templatetags/qfdmd_tags.py
  static/to_compile/styles/dsfr-overrides.css
  templates/components/footer/footer-menu.html
  templates/components/header/header.html
  templates/components/header/header_home.html
  templates/components/header/header_menu.html
  templates/pages/home.html
  templates/qfdmd/base.html
Labels: enhancement, frontend

#1738 🪄 Ajout de rendering conditionnel selon qu'on soit dans une iframe ou non
  .secrets.baseline
  core/settings.py
  core/templatetags/iframe_tags.py
  qfdmd/forms.py
  static/to_compile/controllers/assistant/state.ts
  templates/components/button.html
  templates/components/header/base.html
  templates/components/header/base.iframe.html
  templates/components/header/header.html
  templates/qfdmd/base.html
Labels: enhancement

#1754 🗑️ Suppression de Uvicorn des dépendances
  core/custom_uvicorn_worker.py
  poetry.lock
  pyproject.toml
Labels: technical

#1765 🙈 Correction d'une erreur empêchant l'enregistrement d'un produit depuis Django Admin
  .github/workflows/ci.yml
  Makefile
  e2e_tests/accessibility.spec.ts
  e2e_tests/acteurs.spec.ts
  e2e_tests/assistant.spec.ts
  e2e_tests/carte/advanced_filters.spec.ts
  e2e_tests/carte/legend.spec.ts
  e2e_tests/django-admin.spec.ts
  e2e_tests/formulaire/action_list.spec.ts
  e2e_tests/formulaire/search_update.spec.ts
  e2e_tests/helpers.ts
  e2e_tests/iframe.spec.ts
  integration_tests/carte/test_api.py
  playwright.config.ts
  previews/template_preview.py
  qfdmd/admin.py
  qfdmd/migrations/0039_alter_produit_id.py
  qfdmd/migrations/0040_alter_produit_id.py
  qfdmd/migrations/0041_alter_produit_id.py
  qfdmd/models.py
  qfdmo/management/commands/loaddata_with_computed_fields.py
  templates/components/produit/heading.html
  templates/components/produit/heading_family.html
  templates/qfdmd/produit_page.html
Labels: bug, frontend

#1769 ⎯ Ajout d'une bordure autour des iframes de l'assistant
  templates/qfdmd/base.html
  templates/tests/iframe.html
Labels: frontend

#1783 Corrige un problème sur la recherche en page d'accueil qui entre en conflit avec la recherche dans le menu
  core/context_processors.py
  e2e_tests/assistant.spec.ts
  package-lock.json
  package.json
  qfdmd/forms.py
  qfdmd/views.py
  static/to_compile/controllers/assistant/search.ts
  templates/components/search/view.html
  templates/pages/home.html
Labels: bug

#1785 📚 Réorganisation de la doc : réunoin de tutoriels et comment faire
  docs/comment-faire/README.md
  docs/comment-faire/_medias/troubleshooting-1.png
  docs/comment-faire/data/config-dev-env.md
  docs/comment-faire/data/deployment.md
  docs/comment-faire/deployment.md
  docs/comment-faire/deployment/deployment.md
  docs/comment-faire/development.md
  docs/comment-faire/generer-des-fixtures.md
  docs/comment-faire/infrastructure/scaleway.md
  docs/comment-faire/infrastructure/scaleway_create_db.md
  docs/comment-faire/infrastructure/scaleway_monitoring.md
  docs/comment-faire/prod/commandes.md
  docs/comment-faire/prod/rollback.md
  docs/comment-faire/troubleshooting.md
  docs/conf.py
  docs/tutoriels/README.md
  docs/tutoriels/prod/mise-en-prod.md
Labels: documentation

#1812 Suppression du filtre queryset des vues acteurs
  core/admin.py
  data/admin.py
  qfdmo/admin/acteur.py
Labels: enhancement

#1825 Pas d'option pour déployer lors de review
  .github/workflows/review.yml
  docs/reference/db/prerequis.md
  package-lock.json
  package.json
Labels: bug

#1826 Infrastructure : utilisation de Terragrunt
  .github/workflows/terragrunt_lint.yml
  docs/reference/infrastructure/provisioning.md
  infrastructure/.gitignore
  infrastructure/environments/backend/.terraform.lock.hcl
  infrastructure/environments/backend/main.tf
  infrastructure/environments/backend/terraform.tfvars.example
  infrastructure/environments/backend/variables.tf
  infrastructure/environments/preprod/.terraform.lock.hcl
  infrastructure/environments/preprod/backend.tf
  infrastructure/environments/preprod/main.tf
  infrastructure/environments/preprod/terragrunt.hcl
  infrastructure/environments/preprod/variables.tf
  infrastructure/environments/preview/.terraform.lock.hcl
  infrastructure/environments/preview/backend.tf
  infrastructure/environments/preview/main.tf
  infrastructure/environments/preview/terragrunt.hcl
  infrastructure/environments/preview/variables.tf
  infrastructure/environments/prod/backend.tf
  infrastructure/environments/prod/main.tf
  infrastructure/environments/prod/terragrunt.hcl
  infrastructure/environments/prod/variables.tf
  infrastructure/environments/root.hcl
  infrastructure/environments/variables.tf
  infrastructure/modules/database/main.tf
  infrastructure/modules/database/variables.tf
Labels: enhancement

#1832 Réactiver le déploiement sur les PR
  .github/workflows/review.yml
Labels: technical
