Repository incubateur-ademe/quefairedemesobjets, pull requests merged in 2025-04, with the labels that each got.

#1483 Réponse redirect et non trouvé sur les routes adresse et adresse-details
  integration_tests/qfdmo/test_acteur_detail.py
  qfdmo/views/adresses.py
Labels: bug

#1484 suppression du footer pour les pages 500 et 404
  templates/404.html
  templates/500.html
Labels: bug

#1487 fix page 404 qui génère une 500 car la requete n'a pas de resolver_match
  qfdmd/views.py
Labels: bug

#1492 siren et siret ne peuvent pas être null
  dags/sources/tasks/transform/transform_column.py
  dags/sources/tasks/transform/transform_df.py
  dags_unit_tests/sources/tasks/transform/test_transform_column.py
  dags_unit_tests/sources/tasks/transform/test_transform_df.py
Labels: enhancement

#1494 public_accueilli et reprise ne sont pas null par defaut
  dags/sources/config/shared_constants.py
  dags/sources/tasks/transform/transform_column.py
  dags_unit_tests/sources/tasks/transform/test_transform_column.py
Labels: bug

#1491 🙈 Masquer le bouton infos dans le cas où l'intégrateur est l'ADEME
  jinja2/qfdmo/carte/header.html
  jinja2/qfdmo/carte/panels/legend.html
  static/to_compile/js/iframe.ts
Labels: enhancement

#1497 🤯 L'acteur est mal renseigné lors du partage
  core/constants.py
  core/templatetags/seo_tags.py
  qfdmd/views.py
  unit_tests/core/test_seo_tags.py
Labels: bug, frontend

#1489 🦦 Ajout des sources dans l'API Rest
  core/api.py
  qfdmo/admin/acteur.py
  qfdmo/api.py
  qfdmo/models/acteur.py
Labels: enhancement

#1500 N'afficher qu'un échantillon des Suggestions à supprimer lors de la suppression de cohortes
  data/admin.py
Labels: bug

#1502 le bouton «modifier l'acteur» ne marche pas pour les acteurs parent
  integration_tests/qfdmo/test_adresses_view.py
  integration_tests/qfdmo/test_refresh_acteur_view.py
  qfdmo/models/acteur.py
  qfdmo/urls.py
  qfdmo/views/adresses.py
  templates/admin/base_site.html
Labels: bug

#1504 📉 CLONAGE: relaxer la validation
  dags/clone/config/sql/validation/ae_etablissement/validate_join_acteurs_count_siret.sql
  dags/clone/config/sql/validation/ae_etablissement/validate_rows_count.sql
  dags/clone/config/sql/validation/ae_unite_legale/validate_join_acteurs_count_siren.sql
  dags/clone/config/sql/validation/ae_unite_legale/validate_rows_count.sql
  dags/clone/config/sql/validation/ban_adresses/validate_rows_count.sql
  dags/clone/config/sql/validation/ban_lieux_dits/validate_rows_count.sql
Labels: airflow

#1472 Ré-organisation de la documentation
  .secrets.baseline
  README.airflow.md
  README.md
  dags/acteurs/dags/export_opendata.py
  docs/comment-faire/README.md
  docs/comment-faire/data/config-dev-env.md
  docs/comment-faire/data/deployment.md
  docs/comment-faire/deployment/deployment.md
  docs/comment-faire/development/development.md
  docs/explications/README.md
  docs/explications/data/data-plateform.md
  docs/explications/iframe/iframe.md
  docs/reference/README.md
  docs/reference/db/architecture.md
  docs/reference/iframe/iframe.md
  docs/reference/security.md
Labels: documentation

#1501 📦 CLUSTERING: améliorations diverses
  dags/cluster/config/__init__.py
  dags/cluster/config/constants.py
  dags/cluster/config/model.py
  dags/cluster/config/tasks.py
  dags/cluster/config/xcoms.py
  dags/cluster/dags/cluster_acteur_suggestions.py
  dags/cluster/tasks/airflow_logic/__init__.py
  dags/cluster/tasks/airflow_logic/chain_tasks.py
  dags/cluster/tasks/airflow_logic/cluster_acteurs_clusters_prepare_task.py
  dags/cluster/tasks/airflow_logic/cluster_acteurs_clusters_validate_task.py
  dags/cluster/tasks/airflow_logic/cluster_acteurs_config_create_task.py
  dags/cluster/tasks/airflow_logic/cluster_acteurs_normalize_task.py
  dags/cluster/tasks/airflow_logic/cluster_acteurs_parents_choose_data_task.py
  dags/cluster/tasks/airflow_logic/cluster_acteurs_parents_choose_new_task.py
  dags/cluster/tasks/airflow_logic/cluster_acteurs_read_task.py
  dags/cluster/tasks/airflow_logic/cluster_acteurs_suggestions_prepare_task.py
  dags/cluster/tasks/airflow_logic/cluster_acteurs_suggestions_to_db_task.py
  dags/cluster/tasks/airflow_logic/task_ids.py
  dags/cluster/tasks/business_logic/cluster_acteurs_clusters.py
  dags/cluster/tasks/business_logic/cluster_acteurs_clusters_prepare.py
  dags/cluster/tasks/business_logic/cluster_acteurs_clusters_validate.py
  dags/cluster/tasks/business_logic/cluster_acteurs_config_create.py
  dags/cluster/tasks/business_logic/cluster_acteurs_normalize.py
  dags/cluster/tasks/business_logic/cluster_acteurs_read/__init__.py
  dags/cluster/tasks/business_logic/cluster_acteurs_suggestions/context.py
  dags/cluster/tasks/business_logic/cluster_acteurs_suggestions/prepare.py
  dags/cluster/tasks/business_logic/cluster_acteurs_suggestions/to_db.py
  dags/cluster/tasks/business_logic/misc/cluster_exclude_intra_source.py
  dags/cluster/tasks/business_logic/misc/df_add_original_columns.py
  dags/cluster/tasks/business_logic/misc/df_sort.py
  dags/shared/config/start_dates.py
  dags/tools/dags/airflow_cleanup_db.py
  dags/utils/data_serialize_reconstruct.py
  dags/utils/dataframes.py
  dags/utils/logging_utils.py
  dags_unit_tests/cluster/tasks/business_logic/test_cluster_acteurs_clusters.py
  dags_unit_tests/cluster/tasks/business_logic/test_cluster_acteurs_clusters_add_original_df_columns.py
  dags_unit_tests/cluster/tasks/business_logic/test_cluster_acteurs_clusters_display.py
  dags_unit_tests/cluster/tasks/business_logic/test_cluster_acteurs_suggestions_contexte_generate.py
  dags_unit_tests/cluster/tasks/business_logic/test_cluster_acteurs_suggestions_display.py
  dags_unit_tests/cluster/tasks/business_logic/test_cluster_acteurs_suggestions_to_db_and_apply.py
  dags_unit_tests/e2e/e2e_utils.py
  dags_unit_tests/e2e/test_e2e_dag_cluster_acteurs_airflow.py
  dags_unit_tests/e2e/test_e2e_dag_template_read_db.py
  dags_unit_tests/utils/test_data_serialize_reconstruct.py
  dags_unit_tests/utils/test_dataframes.py
  data/models/changes/acteur_create_as_parent.py
  data/models/changes/acteur_keep_as_parent.py
  data/models/changes/acteur_update_data.py
Labels: bug, enhancement, airflow

#1506 Simplifier le nom des Cohortes
  dags/cluster/dags/cluster_acteur_suggestions.py
  dags/cluster/tasks/airflow_logic/cluster_acteurs_suggestions_to_db_task.py
  dags/crawl/tasks/airflow_logic/crawl_urls_suggest_crawl_diff_other_task.py
  dags/crawl/tasks/airflow_logic/crawl_urls_suggest_crawl_diff_standard_task.py
  dags/crawl/tasks/airflow_logic/crawl_urls_suggest_dns_fail_task.py
  dags/crawl/tasks/airflow_logic/crawl_urls_suggest_syntax_fail_task.py
  dags/crawl/tasks/business_logic/crawl_urls_suggest.py
  dags/sources/tasks/business_logic/db_write_type_action_suggestions.py
  dags_unit_tests/crawl/tasks/business_logic/test_crawl_urls_suggest.py
  data/admin.py
  data/models/suggestion.py
Labels: enhancement

#1485 Ajout d'une colonne par action dans le jeu de données opendata
  dbt/macros/field/sscat_from_action.sql
  dbt/macros/udf/udf_columns_concat_unique_non_empty.sql
  dbt/macros/udf/udf_normalize_string_alpha_for_match.sql
  dbt/macros/udf/udf_safe_divmod.sql
  dbt/macros/udf/udf_uuid_to_int.sql
  dbt/models/exposure/acteurs/opendata/exposure_opendata_acteur.sql
Labels: enhancement

#1517 # 📚 Clustering & dédup: amélioration doc
  docs/reference/README.md
  docs/reference/data/clustering-deduplication.md
Labels: documentation

#1522 J'ai oublié de mettre à jour le test du nombre de colonne
  dbt/models/exposure/acteurs/opendata/schema.yml
Labels: bug

#1521 Comparer les acteurs de la source et en DB via leur source + identifiant_externe
  dags/sources/dags/source_sinoe.py
  dags/sources/tasks/business_logic/keep_acteur_changed.py
  dags/sources/tasks/business_logic/source_data_normalize.py
  dags/sources/tasks/transform/transform_df.py
  dags_unit_tests/sources/tasks/business_logic/test_keep_acteur_changed.py
  docs/comment-faire/README.md
  docs/comment-faire/django/update-ext-id.md
  docs/reference/README.md
  docs/reference/data/gestion-des-identifiants.md
  qfdmo/management/commands/update_external_ids.py
Labels: enhancement

#1475 Ajout des infotris dans l'import export
  qfdmd/admin.py
  qfdmd/models.py
Labels: bug, enhancement

#1490 📍 Faire correspondre icone pinpoint sous categorie
  jinja2/qfdmo/shared/results.html
  qfdmo/models/acteur.py
  unit_tests/qfdmo/test_acteur.py
Labels: enhancement

#1321 🚦 Mise en place de nginx en local
  .env.template
  .github/workflows/ci.yml
  .github/workflows/run_tests.yml
  .gitignore
  .secrets.baseline
  Makefile
  core/context_processors.py
  core/settings.py
  core/views.py
  docker-compose.yml
  e2e_tests/accessibility.spec.ts
  e2e_tests/advanced_filters.spec.ts
  e2e_tests/browser_version.spec.ts
  e2e_tests/carte.spec.ts
  e2e_tests/config.ts
  e2e_tests/iframe.spec.ts
  e2e_tests/iframe/action_list.spec.ts
  e2e_tests/search_update.spec.ts
  integration_tests/core/test_redirects.py
  nginx-local-only/cache.conf
  nginx-local-only/certs/.gitkeep
  nginx-local-only/nginx.conf
  nginx-local-only/servers.conf
  nginx/servers.conf
  playwright.config.ts
  poetry.lock
  pyproject.toml
  qfdmd/middleware.py
  qfdmd/models.py
  qfdmd/urls.py
  qfdmd/views.py
  qfdmo/urls.py
  qfdmo/views/__init__.py
  templates/tests/iframe.html
Labels: frontend, technical

#1549 🔗 Hardcoder les hostnames de l'assistant
  static/to_compile/js/iframe.ts
Labels: bug, frontend

#1550 Résolution de problèmes sur les intégrations par iframe
  .env.template
  .github/workflows/run_tests.yml
  .secrets.baseline
  Makefile
  core/context_processors.py
  core/settings.py
  core/views.py
  docker-compose.yml
  e2e_tests/config.ts
  e2e_tests/iframe.spec.ts
  package-lock.json
  package.json
  playwright.config.ts
  qfdmd/models.py
  qfdmd/templatetags/qfdmd_tags.py
  qfdmo/models/categorie_objet.py
  static/to_compile/entrypoints/assistant/script-to-iframe.ts
  static/to_compile/entrypoints/qfdmd.ts
  static/to_compile/js/search_solution_form_controller.ts
  templates/tests/iframe.html
Labels: bug, frontend

#1554 🦄 Cacher la légende de manière optionnelle dans les cartes sur-mesure
  .pre-commit-config.yaml
  integration_tests/qfdmo/test_carte_config.py
  jinja2/qfdmo/carte/header.html
  jinja2/qfdmo/carte/panels/legend.html
  jinja2/qfdmo/carte/panels/legend_mobile.html
  jinja2/qfdmo/shared/results.html
  qfdmo/migrations/0148_carteconfig_hide_legend.py
  qfdmo/migrations/0149_alter_carteconfig_hide_legend.py
  qfdmo/models/config.py
  qfdmo/views/carte.py
  unit_tests/qfdmo/carte_config_factory.py
Labels: enhancement

#1544 ⏩ [PERF] DBT: modèles unlogged / désactiver le WAL
  dbt/dbt_project.yml
Labels: enhancement, dbt, performance

#1557 🐛 Correction d'une regression sur la redirection vers le CMS
  core/views.py
  integration_tests/core/test_redirects.py
Labels: bug

#1558 😶‍🌫️ Totalement masquer la légende en mobile
  .secrets.baseline
  jinja2/layout/base.html
  jinja2/qfdmo/carte/header.html
  jinja2/qfdmo/carte/panels/legend.html
  static/to_compile/entrypoints/qfdmo.css
Labels: enhancement, frontend

#1559 📏 Correction d'une régression sur la hauteur de la fiche acteur sur une carte sur mesure
  static/to_compile/entrypoints/qfdmo.css
Labels: bug

#1535 🕵 [ENRICH] RGPD: anonymiser les acteurs
  dags/enrich/config/__init__.py
  dags/enrich/config/cohorts.py
  dags/enrich/config/columns.py
  dags/enrich/config/dbt.py
  dags/enrich/config/models.py
  dags/enrich/config/tasks.py
  dags/enrich/config/xcoms.py
  dags/enrich/dags/enrich_acteurs_rgpd.py
  dags/enrich/tasks/business_logic/enrich_dbt_model_to_suggestions.py
  dags_unit_tests/enrich/tasks/test_enrich_suggestions_rgpd.py
  data/migrations/0012_alter_suggestioncohorte_type_action.py
  data/models/changes/__init__.py
  data/models/changes/acteur_rgpd_anonymize.py
  data/models/suggestion.py
  dbt/models/intermediate/acteurs/int_acteur.sql
  dbt/models/intermediate/ae_annuaire_entreprises/int_ae_etablissement.sql
  dbt/models/marts/enrich/marts_enrich_acteurs_closed_replaced.sql
  dbt/models/marts/enrich/marts_enrich_acteurs_rgpd_suggest.sql
  unit_tests/data/models/changes/test_acteur_rgpd_anonymize.py
Labels: enhancement, dbt

#1540 🚀 Amélioration des GitHub actions : environnements, health checks, sécurité
  .github/workflows/_cd-by-environment.yml
  .github/workflows/_deploy-on-clever-cloud.yml
  .github/workflows/_deploy-on-scalingo.yml
  .github/workflows/airflow_deploy_dags.yml
  .github/workflows/cd.yml
  .github/workflows/cd_preprod.yml
  .github/workflows/cd_prod.yml
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  .github/workflows/publish-docs.yml
  .github/workflows/release.yml
  .github/workflows/review.yml
  .github/workflows/run_tests.yml
  .github/workflows/sync_databases.yml
Labels: technical

#1565 📚 Correction de l'action GitHub de déploiement de la doc
  .github/workflows/publish-docs.yml
Labels: documentation, technical, minor

#1566 Re-correction de l'action GH de déploiement de la doc + tentative de correction de l'action de CD
  .github/workflows/ci.yml
  .github/workflows/publish-docs.yml
Labels: frontend, technical

#1567 Supprimer les "yaml anchor" de cd.yml
  .github/workflows/cd.yml
Labels: technical

#1568 Suppression du run de la CI au push sur la main
  .github/workflows/ci.yml
Labels: technical

#1569 correction d'une erreur de syntaxe dans cd.yml
  .github/workflows/cd.yml
Labels: technical

#1570 Correction d'une nouvelle erreur de syntaxe sur la CI/CD
  .github/workflows/cd.yml
Labels: technical

#1572 Encore une correction de syntaxe dans la config CI/CD
  .github/workflows/cd.yml
Labels: github_actions, technical

#1573 Désactiver les tests e2e sur la main temporairement
  .github/workflows/ci.yml
Labels: frontend

#1532 Ajouter un index lors de la résolution de mapping
  dags/sources/tasks/business_logic/keep_acteur_changed.py
  dags_unit_tests/sources/tasks/business_logic/test_keep_acteur_changed.py
  qfdmo/admin/acteur.py
  qfdmo/management/commands/update_external_ids.py
Labels: bug

#1563 Résolution de la configuration SOREN
  dags/sources/dags/source_soren.py
Labels: enhancement

#1561 Support du suffixe pour les acteurs digitaux par les identifiant_externes
  dags/sources/dags/source_aliapur.py
  dags/sources/dags/source_citeo.py
  dags/sources/dags/source_cma.py
  dags/sources/dags/source_corepile.py
  dags/sources/dags/source_cyclevia.py
  dags/sources/dags/source_ecodds.py
  dags/sources/dags/source_ecologic.py
  dags/sources/dags/source_ecomaison.py
  dags/sources/dags/source_ecopae.py
  dags/sources/dags/source_ecosystem.py
  dags/sources/dags/source_ocab.py
  dags/sources/dags/source_ocad3e.py
  dags/sources/dags/source_pharmacies.py
  dags/sources/dags/source_pyreo.py
  dags/sources/dags/source_refashion.py
  dags/sources/dags/source_s3.py
  dags/sources/dags/source_screlec.py
  dags/sources/dags/source_sinoe.py
  dags/sources/dags/source_soren.py
  dags/sources/dags/source_valdelia.py
  dags/sources/tasks/business_logic/keep_acteur_changed.py
  dags/sources/tasks/transform/transform_df.py
  dags_unit_tests/sources/tasks/transform/test_transform_df.py
  qfdmo/migrations/0151_acteur_acteur_unique_by_source_and_external_id.py
  qfdmo/models/acteur.py
Labels: enhancement

#1576 Permettre de décocher la case d'un groupe d'action + afficher la légende en mobile
  jinja2/qfdmo/carte/panels/legend_mobile.html
Labels: bug

#1399 Fix un pb de colonne lors de l'ingestion de SINOE
  dags/sources/dags/source_sinoe.py
  dags/sources/tasks/business_logic/db_read_acteur.py
  dags/sources/tasks/business_logic/keep_acteur_changed.py
  dags/sources/tasks/transform/transform_df.py
  dags/utils/django.py
  dags_unit_tests/conftest.py
  dags_unit_tests/sources/tasks/business_logic/test_keep_acteur_changed.py
  dags_unit_tests/utils/test_django.py
  data/models/suggestion.py
Labels: bug

#1585 Correction des tests e2e
  .github/workflows/ci.yml
  e2e_tests/accessibility.spec.ts
Labels: bug, frontend

#1584 Correction du libelle dans les groupes d'action affichées dans la carte de l'assistant
  qfdmd/models.py
  qfdmo/models/action.py
  qfdmo/views/adresses.py
  templates/forms/widgets/groupe_action_label.html
Labels: frontend

#1583 SOREN et OpeningHours : interpreter les opening_hours
  dags/sources/config/airflow_params.py
  dags/sources/dags/source_soren.py
  dags/sources/tasks/business_logic/source_data_normalize.py
  dags/sources/tasks/transform/opening_hours.py
  dags/sources/tasks/transform/transform_column.py
  dags_unit_tests/sources/tasks/transform/test_transform_column.py
  jinja2/qfdmo/acteur/tabs/sections/horaires.html
Labels: enhancement, minor

#1592 🤖 DBT: script de gestion de schemas
  dags/utils/django.py
  dbt/models/base/ae_annuaire_entreprises/base_ae_unite_legale.sql
  dbt/models/base/ae_annuaire_entreprises/schema.yml
  dbt/models/base/ban/schema.yml
  scripts/dbt/conf/columns.py
  scripts/dbt/conf/schemas.py
  scripts/dbt/schemas_generate_validate.py
  scripts/dbt/tests/test_schemas.py
Labels: enhancement, dbt
