Repository incubateur-ademe/quefairedemesobjets, pull requests merged in 2025-06, with the labels that each got.

#1645 Ne pas prendre en compte le point de localisation pour centrer la carte
  static/to_compile/js/solution_map.ts
Labels: enhancement, minor

#1658 Toujours définir l'url canonique, même si c'est la même url
  qfdmd/templatetags/qfdmd_tags.py
Labels: bug, patch

#1648 Grouper les mises à jour de la ligrairie parcel par dependabot
  .github/dependabot.yml
Labels: technical, minor

#1631 Suppression du module Explorer qui n'est pas exploité
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  .secrets.baseline
  Makefile
  core/settings.py
  core/urls.py
  dags/e2e_tests/e2e_utils.py
  dags/e2e_tests/test_e2e_dag_cluster_acteurs_airflow.py
  dags/e2e_tests/test_e2e_dag_template_read_db.py
  dags/tests/sources/tasks/transform/test_transform_df.py
  poetry.lock
  pyproject.toml
  qfdmo/migrations/0155_remove_explorer_tables.py
Labels: technical

#1671 Correction de la mise à jour du statut des cohortes
  core/admin.py
  data/admin.py
Labels: bug

#1674 Ajout du script Cyclevia
  qfdmo/migrations/0155_alter_carteconfig_slug.py
  qfdmo/migrations/0156_merge_20250605_1531.py
  qfdmo/models/config.py
  static/to_compile/entrypoints/iframe_functions.ts
Labels: frontend

#1675 Revert "Bump @playwright/test from 1.49.1 to 1.52.0 (#1661)"
  package-lock.json
  package.json
Labels: frontend

#1688 Provisioning des bases de données avec OpenTofu
  .github/dependabot.yml
  docs/reference/infrastructure/provisioning.md
  docs/reference/infrastructure/scaleway.md
  infrastructure/.gitignore
  infrastructure/environments/backend/.terraform.lock.hcl
  infrastructure/environments/backend/main.tf
  infrastructure/environments/backend/variables.tf
  infrastructure/environments/preprod/.terraform.lock.hcl
  infrastructure/environments/preprod/backend.tf
  infrastructure/environments/preprod/main.tf
  infrastructure/environments/preprod/terraform.tfvars.example
  infrastructure/environments/preprod/variables.tf
  infrastructure/environments/preview/.terraform.lock.hcl
  infrastructure/environments/preview/backend.tf
  infrastructure/environments/preview/main.tf
  infrastructure/environments/preview/terraform.tfvars.example
  infrastructure/environments/preview/variables.tf
  infrastructure/environments/prod/.terraform.lock.hcl
  infrastructure/environments/prod/backend.tf
  infrastructure/environments/prod/main.tf
  infrastructure/environments/prod/terraform.tfvars.example
  infrastructure/environments/prod/variables.tf
  infrastructure/modules/backend/main.tf
  infrastructure/modules/backend/variables.tf
  infrastructure/modules/database/main.tf
  infrastructure/modules/database/variables.tf
Labels: technical, major

#1707 Oubli de commit sur la première PR open tofu
  infrastructure/environments/backend/main.tf
  infrastructure/environments/preprod/backend.tf
  infrastructure/environments/prod/backend.tf
  infrastructure/modules/backend/main.tf
  infrastructure/modules/backend/variables.tf
Labels: bug, patch

#1709 adaptation de la confguration Ecologic
  dags/sources/config/db_mapping.json
  dags/sources/dags/source_ecologic.py
  dags/sources/tasks/transform/transform_df.py
Labels: enhancement, minor

#1687 Salve de retours sur le maintien de la localisation sur l'assistant
  .gitignore
  .secrets.baseline
  Makefile
  core/context_processors.py
  core/settings.py
  e2e_tests/acteurs.spec.ts
  e2e_tests/assistant.spec.ts
  e2e_tests/search_update.spec.ts
  jinja2/layout/base.html
  jinja2/qfdmo/_addresses_partials/filters/_modal.html
  jinja2/qfdmo/acteur/_action.html
  jinja2/qfdmo/acteur/_action_share.html
  jinja2/qfdmo/acteur/_actions.html
  jinja2/qfdmo/acteur/tabs/_panel.html
  jinja2/qfdmo/acteur/tabs/_tab.html
  jinja2/qfdmo/carte.html
  jinja2/qfdmo/carte/_digital_results.html
  jinja2/qfdmo/carte/panels/acteur_detail.html
  jinja2/qfdmo/carte/panels/legend_mobile.html
  jinja2/qfdmo/carte/results.html
  jinja2/qfdmo/formulaire.html
  jinja2/qfdmo/formulaire/results.html
  jinja2/qfdmo/formulaire/search_form.html
  jinja2/qfdmo/shared/_search_in_zone.html
  qfdmo/management/commands/loadacteurs.py
  qfdmo/models/acteur.py
  static/to_compile/controllers/assistant/analytics.ts
  static/to_compile/controllers/assistant/state.ts
  static/to_compile/controllers/carte/acteur_details.ts
  static/to_compile/controllers/carte/search_solution_form_controller.ts
  static/to_compile/controllers/shared/analytics.ts
  static/to_compile/controllers/shared/analytics_controller.ts
  static/to_compile/js/carte.ts
  static/to_compile/js/solution_map.ts
  static/to_compile/js/types.ts
  static/to_compile/qfdmd.ts
  static/to_compile/qfdmo.ts
  static/to_compile/styles/leaflet-overrides.css
  static/to_compile/svg/pin-background.svg
  templates/components/produit/_detail.html
  templates/qfdmd/base.html
  templates/tests/iframe.html
Labels: bug, frontend

#1676 Documentation de la création de la base de données sur Scaleway
  docs/reference/README.md
  docs/tutoriels/README.md
  docs/tutoriels/infrastructure/scaleway.md
  docs/tutoriels/infrastructure/scaleway_create_db.md
  docs/tutoriels/infrastructure/scaleway_monitoring.md
  scripts/sql/create_schema.sql
Labels: documentation, minor

#1696 Option permettant de garder les données du parent lors d'un clustering avec parent existant
  dags/cluster/config/model.py
  dags/cluster/dags/cluster_acteur_suggestions.py
  dags/cluster/tasks/airflow_logic/cluster_acteurs_parents_choose_data_task.py
  dags/cluster/tasks/business_logic/cluster_acteurs_parents_choose_data.py
  dags/tests/cluster/config/test_model.py
  dags/tests/cluster/tasks/business_logic/test_cluster_acteurs_parents_choose_data.py
Labels: enhancement, minor

#1711 Première lettre de chaque mot de l'adresse et ville en majuscule
  dags/shared/config/tags.py
  dags/sources/config/airflow_params.py
  dags/sources/dags/source_pharmacies.py
  dags/sources/dags/source_s3.py
  dags/sources/tasks/transform/transform_column.py
  dags/sources/tasks/transform/transform_df.py
  dags/tests/sources/tasks/transform/test_transform_column.py
  dags/tests/sources/tasks/transform/test_transform_df.py
  jinja2/qfdmo/acteur.html
  jinja2/qfdmo/acteur/tabs/sections/adresse.html
  qfdmo/management/commands/titlize_acteur_addresses.py
  qfdmo/migrations/0160_titlize_acteur_address.py
Labels: enhancement, minor

#1726 fix relattif à l'utilisation de la DB
  dags/clone/tasks/business_logic/clone_table_create.py
  dags/utils/cmd.py
  qfdmo/management/commands/titlize_acteur_addresses.py
  qfdmo/migrations/0159_connect_public_to_warehouse.py
Labels: bug, patch

#1731 Remise à zero des bbox lorsqu'on mets à jour les données de localisation
  static/to_compile/controllers/assistant/state.ts
  static/to_compile/controllers/carte/search_solution_form_controller.ts
Labels: bug, minor

#1725 Ajout d'une propriété dans PostHog si la visite provient d'une iframe générée par un script
  static/to_compile/controllers/shared/analytics.ts
  static/to_compile/embed/assistant.ts
  static/to_compile/js/helpers.ts
Labels: enhancement

#1732 🐛 Retours sur le maintien de la géoloc dans l'assistant
  jinja2/qfdmo/carte.html
  jinja2/qfdmo/formulaire.html
Labels: bug

#1734 ✨ Amélioration de Prettier
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  package.json
  static/to_compile/admin-map-widget.ts
  static/to_compile/controllers/assistant/blink.ts
  static/to_compile/controllers/assistant/search.ts
  static/to_compile/controllers/carte/acteur_details.ts
  static/to_compile/controllers/carte/address_autocomplete_controller.ts
  static/to_compile/controllers/carte/autocomplete_controller.ts
  static/to_compile/controllers/carte/map_controller.ts
  static/to_compile/controllers/carte/ss_cat_object_autocomplete_controller.ts
  static/to_compile/controllers/shared/analytics.ts
  static/to_compile/controllers/shared/generic_autocomplete_controller.ts
  static/to_compile/embed/assistant.ts
  static/to_compile/embed/carte.ts
  static/to_compile/js/browser_check.ts
  static/to_compile/js/carte.ts
  static/to_compile/js/iframe.ts
  static/to_compile/js/iframe_functions.ts
  static/to_compile/js/parcel.d.ts
  static/to_compile/js/solution_map.ts
  static/to_compile/qfdmd.ts
  static/to_compile/tests/choose_action_controller.test.ts
  static/to_compile/tests/iframe_functions.test.ts
Labels: bug, technical

#1739 💣 Empêcher l'admin de crasher quand on visionne un produit
  qfdmd/admin.py
Labels: bug

#1727 🖊️ Meilleure incitation aux contributions utilisateurs
  core/constants.py
  jinja2/qfdmo/acteur/_actions.html
  jinja2/qfdmo/acteur/tabs/sections/meta.html
  jinja2/qfdmo/carte/panels/legend.html
  jinja2/qfdmo/shared/_search_in_zone.html
  qfdmo/models/acteur.py
  unit_tests/qfdmo/acteur_factory.py
  unit_tests/qfdmo/test_acteur.py
Labels: enhancement, frontend

#1744 Ajout du geste rapporter
  Makefile
  dags/sources/dags/source_citeo.py
  dags/sources/tasks/airflow_logic/config_management.py
  dags/sources/tasks/transform/transform_df.py
  dags/tests/sources/tasks/transform/test_transform_df.py
  integration_tests/carte/test_reemploi_solution.py
  qfdmo/fixtures/actions.json
  qfdmo/migrations/0160_action_rapporter.py
Labels: enhancement, minor
