Repository incubateur-ademe/quefairedemesobjets, pull requests merged in 2025-03, with the labels that each got.

#1398 Suppression de l'enquête dans le footer
  templates/components/footer/_standalone.html
Labels: enhancement

#1382 🔀 Ajouter le comportement de plusieurs sélections de catégories / sous catégories à chaque proposition de service (plutôt que la première)
  static/to_compile/js/controllers/admin/categorie_widget_controller.ts
Labels: bug

#1386 :eye: Vue acteurs: améliorer stabilité
  dags/views/view_acteur_tous.py
Labels: enhancement

#1400 Correction du selecteur parent das l'admin revision acteur
  Makefile
  qfdmo/admin/acteur.py
Labels: bug

#1404 Permettre des slugs de plus de 50 caractères
  qfdmd/migrations/0033_alter_synonyme_slug.py
  qfdmd/models.py
  unit_tests/qfdmd/qfdmod_factory.py
  unit_tests/qfdmd/test_synonyme.py
Labels: bug

#1405 📦 CLUSTERING: fix intra source + rendre fuzzy optionnel
  dags/cluster/config/model.py
  dags/cluster/dags/cluster_acteur_suggestions.py
  dags/cluster/tasks/airflow_logic/cluster_acteurs_clusters_display_task.py
  dags/cluster/tasks/business_logic/cluster_acteurs_clusters.py
  dags/cluster/tasks/business_logic/cluster_acteurs_clusters_display.py
  dags/utils/logging_utils.py
  dags_unit_tests/cluster/config/test_model.py
  dags_unit_tests/cluster/tasks/business_logic/test_cluster_acteurs_clusters.py
  dags_unit_tests/cluster/tasks/business_logic/test_cluster_acteurs_clusters_display.py
Labels: bug, enhancement, python

#1406 Les Picto ne s'affichent plus sur la page d'accueil de QFDMO
  qfdmd/templatetags/qfdmd_tags.py
Labels: bug

#1418 La DB ne doit pas être précisée car différente selon les environnement
  dbt/models/source/source_acteur.yml
Labels: bug

#1425 Suppression de requirements
  .secrets.baseline
  README.airflow.md
  README.md
  airflow-requirements.in
  airflow-requirements.txt
  dbt/README.md
  dev-requirements.in
  dev-requirements.txt
  requirements.in
  requirements.txt
Labels: technical

#1417 Parfois les xlsx envoient des lignes vides, elle doivent être ignorées
  qfdmo/admin/acteur.py
Labels: bug

#1419 Ingestion d'une source à partir d'un fichier xlsx sur s3
  dags/sources/config/airflow_params.py
  dags/sources/dags/source_s3.py
  dags/sources/tasks/airflow_logic/config_management.py
  dags/sources/tasks/airflow_logic/source_data_download_task.py
  dags/sources/tasks/business_logic/db_read_acteur.py
  dags/sources/tasks/business_logic/keep_acteur_changed.py
  dags/sources/tasks/business_logic/source_config_validate.py
  dags/sources/tasks/business_logic/source_data_download.py
  dags/sources/tasks/business_logic/source_data_normalize.py
  dags/sources/tasks/transform/transform_column.py
  dags_unit_tests/sources/tasks/airflow_logic/test_config_management.py
  dags_unit_tests/sources/tasks/business_logic/test_source_data_normalize.py
  dags_unit_tests/sources/tasks/transform/test_transform_column.py
Labels: enhancement

#1420 Renommage de variables lors de processus d'ingestion de sources
  dags/sources/config/airflow_params.py
  dags/sources/dags/source_aliapur.py
  dags/sources/dags/source_citeo.py
  dags/sources/dags/source_cma.py
  dags/sources/dags/source_corepile.py
  dags/sources/dags/source_cyclevia.py
  dags/sources/dags/source_ecodds.py
  dags/sources/dags/source_ecologic.py
  dags/sources/dags/source_ecomaison.py
  dags/sources/dags/source_ecopae.py
  dags/sources/dags/source_ecosystem.py
  dags/sources/dags/source_ocab.py
  dags/sources/dags/source_ocad3e.py
  dags/sources/dags/source_pharmacies.py
  dags/sources/dags/source_pyreo.py
  dags/sources/dags/source_refashion.py
  dags/sources/dags/source_s3.py
  dags/sources/dags/source_screlec.py
  dags/sources/dags/source_sinoe.py
  dags/sources/dags/source_soren.py
  dags/sources/dags/source_valdelia.py
  dags/sources/tasks/business_logic/db_data_prepare.py
  dags/sources/tasks/business_logic/db_read_acteur.py
  dags/sources/tasks/business_logic/keep_acteur_changed.py
  dags/sources/tasks/business_logic/source_data_normalize.py
  dags/sources/tasks/business_logic/source_data_validate.py
  dags/sources/tasks/transform/transform_column.py
  dags/sources/tasks/transform/transform_df.py
  dags_unit_tests/conftest.py
  dags_unit_tests/sources/tasks/business_logic/test_db_data_prepare.py
  dags_unit_tests/sources/tasks/business_logic/test_keep_acteur_changed.py
  dags_unit_tests/sources/tasks/business_logic/test_source_data_normalize.py
  dags_unit_tests/sources/tasks/transform/test_transform_column.py
  dags_unit_tests/sources/tasks/transform/test_transform_df.py
  data/models/suggestion.py
Labels: technical

#1396 ✅ Airflow tests e2e: utilitaires & preuve de concept
  dags/utils/django.py
  dags_unit_tests/cluster/helpers/configs.py
  dags_unit_tests/cluster/helpers/loaders.py
  dags_unit_tests/cluster/tasks/business_logic/test_cluster_acteurs_parents_choose_data.py
  dags_unit_tests/e2e/test_e2e_dag_cluster_acteurs_airflow.py
  dags_unit_tests/e2e/test_e2e_dag_template_read_db.py
  dags_unit_tests/e2e/utils.py
Labels: python, technical

#1407 Suite : Les Picto ne s'affichent plus sur la page d'accueil de QFDMO
  qfdmd/templatetags/qfdmd_tags.py
Labels: bug

#1429 🚨 hotfix airfow scheduler dockerfile
  airflow-scheduler.Dockerfile
Labels: P1, bug, dependencies

#1301 :link: DAG Airflow pour crawler les URLs
  dags/crawl/config/cohorts.py
  dags/crawl/config/columns.py
  dags/crawl/config/constants.py
  dags/crawl/config/tasks.py
  dags/crawl/config/xcoms.py
  dags/crawl/dags/crawl_urls.py
  dags/crawl/tasks/airflow_logic/crawl_urls_check_crawl_task.py
  dags/crawl/tasks/airflow_logic/crawl_urls_check_dns_task.py
  dags/crawl/tasks/airflow_logic/crawl_urls_check_syntax_task.py
  dags/crawl/tasks/airflow_logic/crawl_urls_read_urls_from_db_task.py
  dags/crawl/tasks/airflow_logic/crawl_urls_suggest_crawl_diff_https_task.py
  dags/crawl/tasks/airflow_logic/crawl_urls_suggest_crawl_diff_other_task.py
  dags/crawl/tasks/airflow_logic/crawl_urls_suggest_dns_fail_task.py
  dags/crawl/tasks/airflow_logic/crawl_urls_suggest_syntax_fail_task.py
  dags/crawl/tasks/business_logic/crawl_urls_check_crawl.py
  dags/crawl/tasks/business_logic/crawl_urls_check_dns.py
  dags/crawl/tasks/business_logic/crawl_urls_check_syntax.py
  dags/crawl/tasks/business_logic/crawl_urls_read_urls_from_db.py
  dags/crawl/tasks/business_logic/crawl_urls_suggest.py
  dags/sources/config/shared_constants.py
  dags/utils/dataframes.py
  dags_unit_tests/crawl/fixtures.py
  dags_unit_tests/crawl/tasks/business_logic/test_crawl_urls_check_crawl.py
  dags_unit_tests/crawl/tasks/business_logic/test_crawl_urls_check_dns.py
  dags_unit_tests/crawl/tasks/business_logic/test_crawl_urls_check_syntax.py
  dags_unit_tests/crawl/tasks/business_logic/test_crawl_urls_read_from_db.py
  dags_unit_tests/crawl/tasks/business_logic/test_crawl_urls_suggest.py
  dags_unit_tests/crawl/tasks/business_logic/test_crawl_urls_suggest_metadata.py
  dags_unit_tests/crawl/tasks/business_logic/test_crawl_urls_suggest_prepare.py
  dags_unit_tests/utils/test_dataframes.py
  data/migrations/0008_alter_suggestioncohorte_type_action.py
  data/models/changes/__init__.py
  data/models/changes/acteur_update_data.py
  data/models/suggestion.py
  templates/data/_partials/crawl_urls_suggestion_details.html
  unit_tests/data/models/changes/test_acteur_update_data.py
Labels: enhancement

#1430 Correction de DBT et affichage de proposition de service dans django admin
  dbt/macros/table/macro_filtered_propositionservice.sql
  dbt/macros/table/macro_propositionservice.sql
  dbt/macros/table/macro_propositionservice_sous_categories.sql
  dbt/models/exposure/carte/schema.yml
  qfdmo/admin/acteur.py
Labels: bug

#1431 Fixer la version de python sur Scalingo
  runtime.txt
Labels: bug

#1375 🐦 Ajout de Wagtail et Sites Faciles
  .pre-commit-config.yaml
  .secrets.baseline
  core/context_processors.py
  core/settings.py
  core/urls.py
  docs/reference/data/clustering_deduplication.md
  poetry.lock
  pyproject.toml
  qfdmd/views.py
  templates/qfdmd/base.html
  templates/qfdmd/cmspage_detail.html
  templates/qfdmd/home.html
  templates/qfdmd/synonyme_detail.html
  templates/sites_faciles/base.html
Labels: enhancement, dependencies

#1432 ↪️ Intégrer annuaire entreprises à dbt - v1
  airflow-scheduler.Dockerfile
  dags/clone/config/__init__.py
  dags/clone/config/schemas.py
  dags/clone/config/sql/schemas/tables/schema_table_ae_etablissement.sql
  dags/clone/config/sql/schemas/tables/schema_table_ae_unite_legale.sql
  dags/clone/config/sql/schemas/views/schema_view_clone_ae_etablissement_in_use.sql
  dags/clone/config/sql/schemas/views/schema_view_clone_ae_unite_legale_in_use.sql
  dags/clone/tasks/business_logic/clone_ae_table_create.py
  dags/clone/tasks/business_logic/clone_ae_table_names_prepare.py
  dags/clone/tasks/business_logic/clone_ae_views_in_use_switch.py
  dags_unit_tests/clone/tasks/business_logic/test_clone_ae_table_create.py
  dags_unit_tests/clone/tasks/business_logic/test_clone_ae_table_names_prepare.py
  dags_unit_tests/clone/tasks/business_logic/test_clone_ae_views_in_use_switch.py
  dbt/dbt_project.yml
  dbt/macros/field/acteur_status_is_active.sql
  dbt/macros/udf/udf_columns_concat_unique_non_empty.sql
  dbt/macros/udf/udf_normalize_string_alpha_for_match.sql
  dbt/models/base/ae_annuaire_entreprises/base_ae_etablissement.sql
  dbt/models/base/ae_annuaire_entreprises/base_ae_unite_legale.sql
  dbt/models/base/ae_annuaire_entreprises/schema.yml
  dbt/models/intermediate/ae_annuaire_entreprises/int_ae_etablissement.sql
  dbt/models/intermediate/ae_annuaire_entreprises/int_ae_unite_legale.sql
  dbt/models/intermediate/ae_annuaire_entreprises/schema.yml
  dbt/models/marts/enrich/marts_enrich_ea_rgpd.sql
  dbt/models/marts/enrich/schema.yml
  dbt/models/source/source_ae_annuaire_entreprises.yml
Labels: enhancement, python, dbt

#1443 🦶 Ajout des pages du CMS dans le menu du pied de page
  core/settings.py
  templates/components/footer/_dsfr_footer.html
  templates/components/footer/footer-menu.html
  templates/qfdmd/synonyme_detail.html
Labels: enhancement

#1447 Cleanup old dags and old tests
  dags/annuaire_entreprise_checks.py
  dags/annuaire_entreprise_integration.py
  dags/compute_acteurs/dags/create_final_actors.py
  dags/ingest_validated_dataset_to_db.py
  dags/shared/tasks/airflow_logic/write_data_task.py
  dags/shared/tasks/business_logic/write_data.py
  dags/shared/tasks/database_logic/db_tasks.py
  dags/sources/config/shared_constants.py
  dags/sources/tasks/business_logic/source_data_validate.py
  dags/sources/tasks/transform/read_mapping_from_postgres.py
  dags/sources/tasks/transform/transform_df.py
  dags/utils/api_utils.py
  dags/utils/base_utils.py
  dags/utils/dag_eo_utils.py
  dags/utils/dag_ingest_validated_utils.py
  dags/utils/mapping_utils.py
  dags_unit_tests/sources/tasks/transform/test_transform_df.py
  dags_unit_tests/utils/test_base_utils.py
  dags_unit_tests/utils/test_cmd.py
  dags_unit_tests/utils/test_dag_ingest_validated_utils.py
  dags_unit_tests/utils/test_dags_utils.py
  dags_unit_tests/utils/test_mapping_utils.py
  docs/SOUVENIR.md
Labels: technical

#1436 🧹 DAG Airflow pour nettoyer Airflow
  dags/shared/config/__init__.py
  dags/shared/config/catchups.py
  dags/shared/config/schedules.py
  dags/shared/config/start_dates.py
  dags/tools/dags/airflow_cleanup_db.py
Labels: enhancement, python

#1434 ♻️ Ajout des infotris
  core/constants.py
  qfdmd/management/commands/import_infos_tris.py
  qfdmd/migrations/0034_synonyme_infotri_squashed_0035_remove_synonyme_infotri_produit_infotri.py
  qfdmd/models.py
  templates/components/produit/_infotri.html
  templates/components/produit/produit.html
  templates/qfdmd/synonyme_detail.html
Labels: enhancement, frontend

#1453 🏋️‍♀️ Réduction de la taille du build Scalingo
  .slugignore
Labels: technical

#1455 Suppression de la fonction cluster_strings car elle n'est pas utilisée
  dags/cluster/tasks/business_logic/cluster_acteurs_clusters.py
  dags_unit_tests/cluster/tasks/business_logic/test_cluster_acteurs_clusters.py
Labels: technical

#1463 💥 Correction de l'erreur serveur à l'enregistrement des fiches produit
  qfdmd/admin.py
Labels: bug

#1465 Problème d'erreur serveur sur Wagtail
  core/settings.py
Labels: bug

#1468 Suppression de static du slugignore
  .slugignore
Labels: bug

#1469 Les boutons «Modifier l'acteur» doivent faire la même chose
  qfdmo/admin/acteur.py
  templates/admin/acteur/change_form.html
  templates/admin/displayed_acteur/change_form.html
Labels: enhancement

#1466 par défaut, le start_date des dag est hier : cela évite les rattrapages inutiles
  dags/acteurs/dags/compute_acteur_views.py
  dags/acteurs/dags/export_opendata.py
  dags/clone/dags/clone_ae_annuaire_entreprise.py
  dags/compute_acteurs/dags/create_final_actors.py
  dags/crawl/dags/crawl_urls.py
  dags/sources/tasks/airflow_logic/operators.py
  dags/suggestions/dags/apply_suggestions.py
  dags/tools/dags/airflow_logs.py
  dags/views/view_acteur_tous.py
  dags_unit_tests/e2e/utils.py
  data/admin.py
Labels: technical

#1452 Les colonnes de type Char et Text ne doivent pas être nullable
  dags/sources/tasks/business_logic/source_data_normalize.py
  dags/sources/tasks/transform/transform_df.py
  dags/utils/django.py
  dags_unit_tests/cluster/tasks/business_logic/test_cluster_acteurs_parents_choose_data.py
  dags_unit_tests/cluster/tasks/business_logic/test_cluster_acteurs_read_orphans.py
  dags_unit_tests/crawl/tasks/business_logic/test_crawl_urls_read_from_db.py
  dags_unit_tests/sources/tasks/transform/test_transform_df.py
  qfdmo/migrations/0128_alter_acteur_not_nullable_char_fields.py
  qfdmo/models/acteur.py
  unit_tests/qfdmo/test_acteur.py
Labels: enhancement, technical

#1473 Diviser la grosse migration en plusieurs migrations
  qfdmo/migrations/0128_alter_acteur_not_nullable_char_fields.py
  qfdmo/migrations/0128_alter_acteur_not_nullable_char_fields_adresse.py
  qfdmo/migrations/0129_alter_acteur_not_nullable_char_fields_adresse_complement.py
  qfdmo/migrations/0130_alter_acteur_not_nullable_char_fields_code_postal.py
  qfdmo/migrations/0131_alter_acteur_not_nullable_char_fields_commentaires.py
  qfdmo/migrations/0132_alter_acteur_not_nullable_char_fields_description.py
  qfdmo/migrations/0133_alter_acteur_not_nullable_char_fields_email.py
  qfdmo/migrations/0134_alter_acteur_not_nullable_char_fields_horaires.py
  qfdmo/migrations/0135_alter_acteur_not_nullable_char_fields_identifiant_naf.py
  qfdmo/migrations/0136_alter_acteur_not_nullable_char_fields_noms.py
  qfdmo/migrations/0137_alter_acteur_not_nullable_char_fields_public_reprise.py
  qfdmo/migrations/0138_alter_acteur_not_nullable_char_fields_siren_siret.py
  qfdmo/migrations/0139_alter_acteur_not_nullable_char_fields_tel_url_ville.py
Labels: bug
