Repository incubateur-ademe/quefairedemesobjets, pull requests merged in 2025-09, with the labels that each got.

#1926 Rediriger tous les domaines vers quefairedemesdechets.fr
  .env.template
  .github/workflows/ci.yml
  .secrets.baseline
  APPLICATION.md
  core/context_processors.py
  core/jinja2_handler.py
  core/settings.py
  core/templatetags/script_tags.py
  core/templatetags/share_tags.py
  core/test_settings.py
  core/urls.py
  core/views.py
  docker-compose.yml
  docs/comment-faire/deployment/deployment.md
  docs/comment-faire/development/fixture_generation.md
  docs/explications/frontend/README.md
  docs/explications/iframe/README.md
  e2e_tests/accessibility.spec.ts
  e2e_tests/config.ts
  e2e_tests/iframe.spec.ts
  iframe.html
  iframe_without_js.html
  integration_tests/assistant/home.py
  integration_tests/assistant/synonyme_detail.py
  integration_tests/core/test_redirects.py
  integration_tests/core/test_sharer.py
  nginx-local-only/servers.conf
  playwright.config.ts
  previews/template_preview.py
  qfdmd/middleware.py
  qfdmd/templatetags/qfdmd_tags.py
  qfdmo/urls.py
  qfdmo/views/adresses.py
  qfdmo/views/auth.py
  servers.conf.erb
  templates/modals/share.html
  templates/seo/_canonical_url.html
  templates/tests/iframe.html
  unit_tests/core/test_seo_tags.py
  unit_tests/qfdmo/test_views.py
Labels: frontend, seo

#1899 Adaptation du Makefile pour la gestion des 2 bases de données
  Makefile
  bin/post_deploy
Labels: technical

#1644 Ajout du context dans les réponses quand on cherche une ville
  static/to_compile/controllers/carte/address_autocomplete_controller.ts
  static/to_compile/controllers/carte/autocomplete_controller.ts
  static/to_compile/controllers/carte/ss_cat_object_autocomplete_controller.ts
  templates/forms/widgets/autocomplete.html
Labels: enhancement, frontend, minor

#1970 ajoutes des colonnes consignes d'accès et horaires au jeu de données opendata
  dbt/models/exposure/acteurs/opendata/exposure_opendata_acteur.sql
  dbt/models/exposure/acteurs/opendata/schema.yml
Labels: enhancement

#1967 Infra Airflow preprod : nom du bucket S3 pour logs
  infrastructure/modules/container/airflow-webserver.tf
Labels: technical, airflow

#1975 Ajustements Airflow preprod
  infrastructure/environments/preprod/container/terragrunt.hcl
  infrastructure/modules/container/airflow-scheduler.tf
  infrastructure/modules/container/airflow-webserver.tf
  infrastructure/modules/container/variables.tf
Labels: technical, airflow

#1990 Modifier les 301 en 302
  integration_tests/core/test_redirects.py
  nginx-local-only/servers.conf
  qfdmd/middleware.py
  servers.conf.erb
Labels: enhancement, frontend, minor

#1944 Migration de Leaflet -> Maplibre
  .github/workflows/ci.yml
  .github/workflows/review.yml
  .tool-versions
  Makefile
  core/settings.py
  core/templatetags/qfdmo_tags.py
  docs/comment-faire/development/installation.md
  docs/comment-faire/development/useful_command.md
  e2e_tests/acteurs.spec.ts
  e2e_tests/assistant.spec.ts
  e2e_tests/carte/advanced_filters.spec.ts
  e2e_tests/carte/legend.spec.ts
  e2e_tests/django-admin.spec.ts
  e2e_tests/formulaire/search_update.spec.ts
  e2e_tests/helpers.ts
  e2e_tests/iframe.spec.ts
  integration_tests/carte/test_adresses_view.py
  nginx-local-only/servers.conf
  notebooks/20241031_acteurs_inactifs_reparation_lvao_ancien_cma.ipynb
  package-lock.json
  package.json
  previews/template_preview.py
  qfdmo/map_utils.py
  qfdmo/migrations/0164_rebuild_remote_server.py
  qfdmo/migrations/0166_update_objets_code.py
  qfdmo/models/acteur.py
  qfdmo/views/adresses.py
  static/to_compile/controllers/carte/acteur_details.ts
  static/to_compile/controllers/carte/map_controller.ts
  static/to_compile/js/solution_map.ts
  static/to_compile/js/types.ts
  static/to_compile/styles/carte.css
  static/to_compile/styles/leaflet-overrides.css
  static/to_compile/styles/maplibre-overrides.css
  static/to_compile/svg/bonus-reparation-fill.svg
  static/to_compile/svg/pin-background-fill.svg
  static/to_compile/svg/pin-background.svg
  templates/components/carte/carte.html
  templates/components/produit/_detail.html
  templates/qfdmo/carte/pinpoints/acteur.html
  templates/qfdmo/carte/pinpoints/home.html
  templates/qfdmo/carte/pinpoints/svg/bonus-icon.svg
  templates/qfdmo/carte/pinpoints/svg/pin-background-fill.html
  templates/qfdmo/carte/pinpoints/svg/pin-background.html
  templates/qfdmo/carte/results.html
  templates/qfdmo/formulaire/results.html
  unit_tests/core/test_qfdmo_tags.py
  unit_tests/qfdmo/carte_config_factory.py
  unit_tests/qfdmo/test_acteur.py
  unit_tests/qfdmo/test_carte_config.py
Labels: frontend, technical, major

#1992 ajout de champs d'information sur la vue exhaustive des acteurs
  dags/acteurs/dags/compute_acteur.py
  dbt/models/exposure/acteurs/exhaustive/schema.yml
  dbt/models/marts/acteurs/exhaustive/marts_exhaustive_acteur.sql
  dbt/models/marts/acteurs/exhaustive/schema.yml
  qfdmo/admin/acteur.py
  qfdmo/migrations/0172_vueacteur_enfants_liste_vueacteur_enfants_nombre_and_more.py
  qfdmo/models/acteur.py
Labels: enhancement, minor

#1978 Résolution de l'affichage du detail exact match quand il n'y a qu'un champ
  dags/cluster/tasks/business_logic/cluster_acteurs_suggestions/context.py
Labels: bug, patch

#1974 Les données des révisions sont prioritaires pour choisir les données du parent
  dags/cluster/tasks/business_logic/cluster_acteurs_parents_choose_data.py
  dags/tests/cluster/tasks/business_logic/test_cluster_acteurs_parents_choose_data.py
  dags/tests/cluster/tasks/business_logic/test_cluster_acteurs_read_children.py
Labels: bug, patch

#1993 Migration de POETRY vers UV
  .github/workflows/ci.yml
  .github/workflows/publish-docs.yml
  Makefile
  Procfile.all.dev
  Procfile.django.dev
  airflow-scheduler.Dockerfile
  airflow-webserver.Dockerfile
  dbt/README.md
  docs/comment-faire/development/dependencies.md
  docs/comment-faire/development/installation.md
  docs/comment-faire/troubleshooting.md
  poetry.lock
  poetry.toml
  pyproject.toml
  uv.lock
Labels: technical, minor

#1998 Finalisation fix tests e2e
  e2e_tests/assistant.spec.ts
  e2e_tests/helpers.ts
  templates/qfdmo/carte/results.html
Labels: frontend

#2003 Ajouter un id sur l'iframe de l'assistant pour éviter des conflits avec iframe resizer
  static/to_compile/embed/assistant.ts
Labels: frontend

#2007 Ne pas afficher les Acteurs qui ne font que du service à domicile
  dbt/models/exposure/acteurs/carte/exposure_carte_acteur.sql
Labels: bug, patch

#2008 Petite typo lors de l'ingestion de service à domicile
  data/models/suggestion.py
Labels: bug

#2009 L'import s3 est cassé depuis l'intégration des service à domicile
  data/models/suggestion.py
  unit_tests/qfdmd/test_synonyme.py
Labels: bug

#2000 Nouveau DAG pour suggérer des corrections de codes postaux
  dags/enrich/config/cohorts.py
  dags/enrich/config/columns.py
  dags/enrich/config/tasks.py
  dags/enrich/config/xcoms.py
  dags/enrich/dags/enrich_acteurs_normalize_codepostal.py
  dags/enrich/tasks/airflow_logic/db_read_acteur_cp_task.py
  dags/enrich/tasks/airflow_logic/db_write_cp_suggestions_task.py
  dags/enrich/tasks/airflow_logic/normalize_acteur_cp_task.py
  dags/enrich/tasks/business_logic/db_read_acteur_cp.py
  dags/enrich/tasks/business_logic/db_write_cp_suggestions.py
  dags/enrich/tasks/business_logic/enrich_dbt_model_to_suggestions.py
  dags/enrich/tasks/business_logic/normalize_acteur_cp.py
  dags/tests/enrich/tasks/test_db_read_acteur_cp.py
  dags/tests/enrich/tasks/test_normalize_acteur_cp.py
  data/migrations/0014_alter_suggestioncohorte_type_action.py
  data/models/changes/__init__.py
  data/models/changes/acteur_update.py
  data/models/suggestion.py
  docs/explications/data/README.md
  unit_tests/data/models/changes/test_acteur_update.py
Labels: enhancement, minor

#2005 Ajout de la déclaration d'accessibilité à la carte
  core/context_processors.py
  core/settings.py
  qfdmd/templatetags/qfdmd_tags.py
  templates/qfdmo/carte/_declaration_accessibilite.html
  templates/qfdmo/carte/panels/legend.html
  templates/qfdmo/carte/results.html
Labels: enhancement, frontend

#2029 Flaguer les sous-categories réemployables ou non
  qfdmo/admin/categorie_objet.py
  qfdmo/management/commands/type_souscategorieobjets.py
  qfdmo/migrations/0174_souscategorieobjet_reemploi_possible.py
  qfdmo/models/categorie_objet.py
Labels: enhancement, minor

#2031 Rechercher avancé des acteurs dans Django admin
  core/settings.py
  pyproject.toml
  qfdmo/admin/acteur.py
  uv.lock
Labels: enhancement, minor

#2033 Report d'un fix qu'on a perdu lors de l'abandon de Jinja
  core/jinja2_handler.py
  core/templatetags/qfdmo_tags.py
Labels: bug

#2035 Correction des test e2e
  core/settings.py
  e2e_tests/assistant.spec.ts
  playwright.config.ts
  templates/analytics/posthog_data_attributes.html
  templates/qfdmd/base.html
Labels: frontend

#2022 CD : déploiement de Airflow sur Clever en prod uniquement
  .github/workflows/_deploy-airflow.yml
Labels: technical, airflow

#2050 Recherche des objets dans la table Synonyme
  integration_tests/formulaire/test_routes.py
  qfdmo/migrations/0175_alter_objet_options.py
  qfdmo/models/categorie_objet.py
  qfdmo/urls.py
  qfdmo/views/adresses.py
  static/to_compile/controllers/carte/ss_cat_object_autocomplete_controller.ts
  templates/qfdmo/_addresses_partials/filters/_object_filter.html
  templates/qfdmo/formulaire/search_form.html
  unit_tests/qfdmo/test_adresse_get_object_list.py
Labels: enhancement

#2049 Amelioration admin wagtail - 23/9 - Redirections, homepage, recherche
  core/context_processors.py
  core/notion.py
  core/settings.py
  core/utils.py
  previews/template_preview.py
  qfdmd/admin.py
  qfdmd/apps.py
  qfdmd/forms.py
  qfdmd/middleware.py
  qfdmd/migrations/0060_alter_produit_options_alter_synonyme_options_and_more.py
  qfdmd/migrations/0061_legacyintermediateproduitpage.py
  qfdmd/migrations/0062_formpagevalidationsettings.py
  qfdmd/models.py
  qfdmd/signals.py
  qfdmd/templatetags/qfdmd_tags.py
  qfdmd/views.py
  qfdmo/migrations/0175_carteconfig_direction.py
  qfdmo/migrations/0176_merge_20250924_1802.py
  qfdmo/models/config.py
  qfdmo/views/adresses.py
  templates/base.html
  templates/components/header/header.html
  templates/components/produit/heading.html
  templates/components/search/view.html
  templates/pages/home.html
  templates/qfdmd/family_page.html
  templates/qfdmd/produit_page.html
  templates/sites_faciles/base.html
  unit_tests/qfdmd/test_genre_nombre_model.py
  unit_tests/qfdmd/test_middleware.py
Labels: enhancement, frontend, minor

#2062 Désactiver le backlink temporairement
  static/to_compile/embed/helpers.ts
Labels: frontend

#2063 Backlink le retour
  core/settings.py
  core/views.py
  static/to_compile/embed/helpers.ts
Labels: enhancement
