Repository incubateur-ademe/quefairedemesobjets, pull requests merged in 2025-02, with the labels that each got.

#1348 Proposition de template selon les habitudes de @max + labels
  .github/pull_request_template.md
Labels: technical

#1346 Si il n'y a pas de query lors de l'appel à get_objet_list alors on retourne une liste vide d'objet
  qfdmo/views/adresses.py
  unit_tests/qfdmo/test_adresse_get_object_list.py
Labels: frontend

#1351 Permettre de créer un parent même quand une action principale est définie
  qfdmo/models/acteur.py
  unit_tests/qfdmo/test_acteur.py
Labels: bug

#1372 Augmenter ne nombre de valeurs accepté dans la requête 1000 -> 10000
  .env.template
  core/settings.py
Labels: bug

#1370 script de ratrappage par source des propositions de service
  qfdmo/management/commands/enrich_revisionpropositionservice.py
Labels: enhancement

#1377 Suppression des warnings du DAG et organisation de .env.template
  dags/.env.template
  dags/cluster/tasks/business_logic/cluster_acteurs_suggestions/contexte.py
  dags/utils/django.py
Labels: technical

#1349 Ajout de l'encodage de la Pk sur les liens vers l'admin + gestion de la depreciation de l'utilisation de format_html
  data/admin.py
  qfdmo/admin/acteur.py
Labels: technical

#1371 Permettre les Valeurs __empty__ dans les formulaires
  core/validators.py
  qfdmo/migrations/0122_alter_revisionacteur_email.py
  qfdmo/models/acteur.py
  unit_tests/qfdmo/test_acteur.py
Labels: bug

#1373 Fusionner les duplicats des sources
  dags/sources/dags/source_aliapur.py
  dags/sources/dags/source_citeo.py
  dags/sources/dags/source_cma.py
  dags/sources/dags/source_corepile.py
  dags/sources/dags/source_cyclevia.py
  dags/sources/dags/source_ecodds.py
  dags/sources/dags/source_ecologic.py
  dags/sources/dags/source_ecomaison.py
  dags/sources/dags/source_ecopae.py
  dags/sources/dags/source_ecosystem.py
  dags/sources/dags/source_ocab.py
  dags/sources/dags/source_ocad3e.py
  dags/sources/dags/source_pyreo.py
  dags/sources/dags/source_refashion.py
  dags/sources/dags/source_screlec.py
  dags/sources/dags/source_sinoe.py
  dags/sources/dags/source_soren.py
  dags/sources/dags/source_valdelia.py
  dags/sources/tasks/airflow_logic/config_management.py
  dags/sources/tasks/business_logic/source_data_normalize.py
  dags/sources/tasks/transform/transform_df.py
  dags_unit_tests/sources/tasks/airflow_logic/test_config_management.py
  dags_unit_tests/sources/tasks/business_logic/test_source_data_normalize.py
  dags_unit_tests/sources/tasks/transform/test_transform_df.py
Labels: enhancement

#1356 Ne pas permettre la création ou la suppression d'acteur parent sur le select
  core/admin.py
  qfdmo/admin/acteur.py
  qfdmo/migrations/0123_revisionacteurparent_alter_revisionacteur_parent.py
  qfdmo/models/acteur.py
Labels: bug

#1326 Nettoyage des anciennes interface de validation
  .github/workflows/sync_databases.yml
  core/urls.py
  dags/sources/tasks/airflow_logic/compute_link_tables_task.py
  dags/sources/tasks/airflow_logic/db_data_prepare_task.py
  dags/sources/tasks/airflow_logic/operators.py
  dags/sources/tasks/airflow_logic/propose_acteur_changes_task.py
  dags/sources/tasks/business_logic/compute_link_tables.py
  dags/sources/tasks/business_logic/db_data_prepare.py
  dags/sources/tasks/business_logic/propose_acteur_changes.py
  dags_unit_tests/sources/tasks/business_logic/test_compute_link_tables.py
  dags_unit_tests/sources/tasks/business_logic/test_db_data_prepare.py
  dags_unit_tests/sources/tasks/business_logic/test_propose_acteur_changes.py
  data/admin.py
  data/forms.py
  data/urls.py
  data/views.py
  integration_tests/core/test_redirects.py
  jinja2/qfdmo/create_actor_event.html
  jinja2/qfdmo/dags_validations.html
  jinja2/qfdmo/partials/candidat_row.html
  jinja2/qfdmo/update_actor_event.html
  qfdmo/forms.py
  qfdmo/management/commands/reinitialize_dagrun.py
  qfdmo/management/commands/reinitialize_suggestions.py
  qfdmo/migrations/0124_remove_dagrunchange_dag_run_delete_dagrun_and_more.py
  qfdmo/models/__init__.py
  qfdmo/models/data.py
  qfdmo/urls.py
  qfdmo/views/dags.py
  templates/data/_partials/source_ajout_event.html
  templates/data/_partials/source_event.html
  templates/data/_partials/source_supression_event.html
  templates/data/_partials/suppression_suggestion_details.html
  templates/data/_partials/update_actor_event.html
  templates/data/_partials/value_details.html
  templates/data/base.html
  templates/data/dags_validations.html
Labels: technical

#1378 Suppression d'un reverse en trop
  qfdmo/admin/acteur.py
Labels: bug

#1379 🔇CLUSTERING: exclure les enfants existants du contexte
  dags/cluster/tasks/business_logic/cluster_acteurs_suggestions/contexte.py
  dags_unit_tests/cluster/tasks/business_logic/test_cluster_acteurs_suggestions_contexte_generate.py
Labels: bug, python

#1381 🔍 Ajout de champs d'autocomplétion sur les produits / liens et synonymes
  qfdmd/admin.py
Labels: enhancement
